# Generated by Django 4.1.3 on 2022-11-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='uniqueid',
            new_name='id',
        ),
    ]
