# Generated by Django 4.1.3 on 2022-11-19 20:11

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_bookinstance_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='nationality',
        ),
        migrations.AddField(
            model_name='author',
            name='nationality',
            field=django_countries.fields.CountryField(default='GH', max_length=746, multiple=True),
            preserve_default=False,
        ),
    ]
