# Generated by Django 4.1.3 on 2022-11-19 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_author_nationality_author_nationality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nationality',
        ),
    ]
