# Generated by Django 4.1.3 on 2022-11-27 17:33

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_delete_nationality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'permissions': (('can_add_book', 'Can add book'),)},
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='died'),
        ),
        migrations.AlterField(
            model_name='author',
            name='nationality',
            field=django_countries.fields.CountryField(help_text='Hold down “Control”, or “Command” on a Mac, to select more than one.', max_length=746, multiple=True),
        ),
    ]
