# Generated by Django 4.1.3 on 2022-11-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_book_options_alter_author_date_of_death_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'permissions': (('can_add_new_book', 'Can add new book'),)},
        ),
    ]
