# Generated by Django 4.1.3 on 2022-11-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'permissions': (('can_add_book', 'Can add new book'),)},
        ),
    ]
