# Generated by Django 4.1.3 on 2023-02-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_alter_book_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="date_of_birth",
            field=models.DateField(blank=True, help_text="YYYY-MM-DD", null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="date_of_death",
            field=models.DateField(
                blank=True, help_text="YYYY-MM-DD", null=True, verbose_name="died"
            ),
        ),
        migrations.AlterField(
            model_name="bookinstance",
            name="due_back",
            field=models.DateField(blank=True, help_text="YYYY-MM-DD", null=True),
        ),
    ]
